services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=pharmaconnect
    ports:
      - "5432:5432"
    volumes:
      - mydbdata:/var/lib/postgresql

volumes:
  mydbdata: