-- Auto-generated SQL INSERT statements for items table
-- Generated from pharmacy_data.json

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('fe032b75-9064-4677-8e55-37c6394b204c', 'Nurofen Express 200 mg, 20 capsules, Reckitt Benckiser', 'Nurofen Express soft capsules quickly soothe headaches, migraines, muscle or rheumatic pains. Pain relief also depends on how easily the medicine is broken down and absorbed in the body. Nurofen Express 200 mg soft capsules are quickly absorbed by the body, targeting the painful area. Due to its composition, Nurofen Express calms quickly and makes its effect promptly and effectively right at the source of the pain. This way you regain your well-being and you can enjoy every moment.

Nurofen Express 200 mg soft capsules is quickly absorbed by the body, the outer gel layer begins to disintegrate very quickly in the stomach, allowing the liquid ibuprofen to disperse in the small intestine, acting quickly against fever and pain. Nurofen Express contains 200 mg of ibuprofen and is used to treat headaches, backaches, flu and cold symptoms, febrile conditions, menstrual and dental pains, neuralgia, migraines, muscle and rheumatic pains.', 'Medicines without a prescription', 30.49, 'NUROFEN', 'https://www.drmax.ro/_i/-1315687461.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2F7%2F6%2F763c8c9c45c26_rb_nurofen_carton_200mg_rbl2004920_3157624_oop.jpg&fit=contain&w=350&h=350&format=webp', '2025-01-01', '2027-01-01', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('c88b5095-fb1f-4a97-a4d1-1fbb4597b3fa', 'Nurofen Express, 200 mg, 20 soft capsules, Reckitt Benckiser', 'Indications: Nurofen Express is used to: - relieve mild to moderate pain, such as headaches, toothaches and - reduce fever and pain associated with the common cold.

Contraindications: Do not take Nurofen Express - if you are allergic (hypersensitive) to ibuprofen, Ponceau 4R (E124) or any of the other components of Nurofen Express.', 'Analgesics', 30.5, 'Nurofen', 'https://media.farmaciatei.ro/gallery/15802/medium/nurofen-express-200mg-20-capsule-reckitt-benckiser-healthcare-9410.jpg', '2025-01-01', '2027-02-28', TRUE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('8334a8a8-749f-4e2d-bbf9-75f3a07db952', 'Nurofen Express 200 mg x 20 soft capsules (Reckitt Benckiser)', 'Nurofen express 200 mg soft capsules is used to relieve mild to moderate pain, has an anti-inflammatory, analgesic, antipyretic effect. It acts quickly on the source of the pain and is quickly absorbed into the bloodstream', 'inflammatory', 32.0, 'RECKITT BENCKISER', 'https://c.cdnmp.net/767429209/p/l/8/nurofen-expres-200-mg-x-20capsule-moi-reckitt-benckiser~3608.jpg', '2025-01-01', '2027-01-01', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('fda76138-60f4-4544-b2e7-71788a312b77', 'Paracetamol 500mg, 20 tablets, Zentiva', 'Paracetamol Zentiva belongs to the group of analgesic-antipyretic drugs (relieves pain and reduces body temperature in case of fever).

Paracetamol Zentiva is indicated in the symptomatic treatment of pain of mild to moderate intensity, with different locations (headaches, sore throat, toothaches, pains associated with colds and flu, muscle or joint pains or in case of painful menstruation) and the symptomatic treatment of fever.', 'Medicines without a prescription', 2.49, 'ZENTIVA', 'https://www.drmax.ro/_i/-878797291.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2F1%2F2%2F1200x1200_px_paracetamol_zentiva_dr.jpg&fit=contain&w=350&h=350&format=webp', '2025-01-01', '2027-01-01', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('bd154714-9758-4e08-bc15-0b44da2ad617', 'Paracetamol, 500 mg, 20 tablets, Zentiva', 'Indications:- Paracetamol Zentiva is part of the group of analgesic-antipyretic drugs (relieves pain and reduces body temperature in case of fever);- Paracetamol Zentiva is indicated in the symptomatic treatment of pain of mild to moderate intensity, with different locations (headaches, sore throat, toothache, pain associated with cold and flu, muscle or joint pain or in case of painful menstruation) and the symptomatic treatment of fever.

Contraindications: Do not take Paracetamol Zentiva: - if you are allergic to paracetamol or any of the other components of this medicine;', 'Relief of cold and flu symptoms', 1.5, 'Zentiva', 'https://media.farmaciatei.ro/gallery/15454/paracetamol-500-mg-20-comprimate-zentiva-3642.jpg', '2025-01-01', '2026-09-30', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('93f9d1d2-3c67-4083-8c01-b332617582a5', 'Strepsils honey and lemon, 24 tablets, Reckitt Benckiser', 'What is Strepsils Honey and Lemon and what it is used for:

Strepsils Honey and Lemon belongs to a group of medicines called antiseptics. Strepsils Honey and Lemon is used as an adjuvant in the treatment of oropharyngeal infections, favoring the relief of the symptoms caused by them. Quick (in 5 minutes) and long-lasting (up to 2 hours) relief of sore throat. Antibacterial, antifungal and antiviral effect.', 'Medicines without a prescription', 24.49, 'STREPSILS', 'https://www.drmax.ro/_i/-694494302.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2Fs%2Ft%2Fstrepsils_mi_si_lamaie.jpg&fit=contain&w=350&h=350&format=webp', '2025-01-01', '2027-01-01', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('bceea1c7-3c83-4a37-8370-66f886540255', 'Strepsils honey and lemon, 24 tablets, Reckitt Benckiser', 'Indications: Strepsils Honey and Lemon belongs to a group of drugs called antiseptics. Strepsils Honey and Lemon is used as an adjuvant in the treatment of oropharyngeal infections, favoring the relief of the symptoms caused by them. Rapid (in 5 minutes) and long-lasting (up to 2 hours) relief of sore throat. Antibacterial, antifungal and antiviral effect.

Contraindications: Do not take Strepsils Honey and Lemon: - if you are allergic (hypersensitive) to amylmetacresol and 2,4-dichlorobenzyl alcohol or to any of the other components of the medicine.', 'Neck pain', 24.5, 'Strepsils', 'https://media.farmaciatei.ro/gallery/15789/medium/strepsils-miere-si-lamaie-24-comprimate-reckitt-benckiser-healthcare-1913.jpg', '2025-01-01', '2028-04-01', TRUE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('5df9a655-5313-46f1-a869-b70595813b0f', 'Strepsils Honey&Lemon x24 tablets, Reckitt Benckiser Healthcare', 'Strepsils Honey and Lemon provide fast and effective relief of sore throats, acting from the first signs of pain. Its formula includes antiseptic ingredients to fight bacterial infections and is enriched with honey and lemon for an emollient effect and a pleasant aroma.', 'Neck pain', 22.0, 'RECKITT BENCKISER', 'https://c.cdnmp.net/767429209/p/l/3/strepsils-miere-lamaie-x24-comprimate-reckitt-benckiser-healthcare~5523.jpg', '2025-01-01', '2027-01-01', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('4326d34e-ff9d-4e8f-b715-652a1e32e79a', 'Coldrex Maxgrip Lemon, 10 sachets, Perrigo', 'What is Coldrex MaxGrip Lemon and what is it used for

Coldrex MaxGrip Lemon is a medicine against cold and flu that contains three active substances: - paracetamol that relieves pain and reduces the temperature when you have a fever; - phenylephrine hydrochloride is a decongestant that unclogs the nose and sinuses and helps you breathe easier; - vitamin C (ascorbic acid) replaces vitamin C that is lost in the first stages of cold and flu. Coldrex MaxGrip Lemon is a remedy used for symptomatic relief, on short term, of flu, febrile conditions, chills and common colds, including headache, sore throat, discomfort and pain in the limbs, nasal congestion, sinusitis and associated pain.', 'Medicines without a prescription', 34.49, 'PERRIGO', 'https://www.drmax.ro/_i/-1185679539.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2F2%2F6%2F2662289ec2af5_frontofpack.png&fit=contain&w=350&h=350&format=webp', '2025-01-01', '2027-01-01', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('6a125ae4-564f-49c6-8317-21c6520ffc02', 'Coldrex Maxgrip Lemon, 10 sachets, Perrigo', 'Indications: Coldrex Maxgrip Lemon is a cold and flu medicine that contains three active substances: - paracetamol that relieves pain and reduces the temperature when you have a fever; - phenylephrine hydrochloride is a decongestant that unclogs the nose and sinuses and helps you breathe easier; - vitamin C (ascorbic acid) replaces vitamin C that is lost in the first stages of colds and flu.

Coldrex Maxgrip Lemon is a remedy used for the short-term symptomatic relief of flu, febrile conditions, chills and common colds, including headache, sore throat, discomfort and pain, nasal congestion, sinusitis as well as pain and acute nasal catarrh associated with it.', 'Relief of cold and flu symptoms', 34.5, 'Perrigo Otc', 'https://media.farmaciatei.ro/images/products-photos/medium/coldrex-maxgrip-lemon-10-plicuri-perrigo-4619.jpg', '2025-01-01', '2027-05-01', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('a3559fdb-41c9-4684-80d2-85bc3834078b', 'Aspacardin, 30 tablets, Terapia', 'What is Aspacardin and what is it used for

Aspacardin belongs to the group of medicines called mineral supplements, potassium medicines. It acts on the heart and blood vessels, being used as an adjunctive therapy in adults in coronary disease (disease of the blood vessels of the heart), in certain cardiac rhythm disorders and for the prevention of cardiac rhythm disorders that may occur after treatment with some drugs called tonic-cardiac glycosides.', 'Medicines without a prescription', 24.49, 'TERAPIA', 'https://www.drmax.ro/_i/-1746787120.webp?m2=%2Fmedia%2Fcatalog%2Fproduct%2Fb%2Fe%2Fbe21cb87fcee5_5944702001789.jpg&fit=contain&w=350&h=350&format=webp', '2025-01-01', '2027-01-01', FALSE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('aec7e00a-3c49-4763-a452-f1443b14da18', 'Aspacardin, 39 mg/12, 30 tablets, Terapia', 'Indications: Aspacardin is part of the group of drugs called mineral supplements, potassium drugs. It acts on the heart and blood vessels and is used as adjunctive therapy in adults in coronary heart disease (disease of the blood vessels of the heart), in certain cardiac rhythm disorders and for the prevention of heart rhythm disorders that may occur after treatment with some drugs called tonic-cardiac glycosides.

Contraindications: Do not use Aspacardin: - if you are allergic (hypersensitive) to the active substances or to any of the other components of Aspacardin.', 'Cardiac and blood pressure', 24.5, 'Terapia Sa', 'https://media.farmaciatei.ro/gallery/15333/medium/aspacardin-30-comprimate-terapia-8098.jpg', '2025-01-01', '2028-04-01', TRUE, 'No known side effects', 0, 100);

INSERT INTO items (id, name, description, category, price, brand, image_url, manufacturing_date, expiration_date, prescription_required, side_effects, sold_count, stock_quantity) VALUES
('c7a1103c-300a-43b3-9d60-be155cdde12c', 'Aspacardin 39 mg/12 mg x 30 tablets (Therapy)', 'Aspacardin belongs to the group of drugs called mineral supplements, potassium drugs that act on the heart and blood vessels', 'Cardiac and Blood Pressure', 16.5, 'Terapia', 'https://c.cdnmp.net/767429209/p/l/2/aspacardin-39-mg-12-mg-x-30-comprimate-terapia~1562.jpg', '2025-01-01', '2027-01-01', FALSE, 'No known side effects', 0, 100);

