spring.application.name=Pharmacy-Manager

# Database - Postresql
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmaconnect
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=public
spring.flyway.schemas=public
openapi.api.url=https://api.openai.com/v1/chat/completions
openapi.api.model=gpt-4o-mini
openapi.api.key=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
