spring.application.name=Pharmacy-Manager

# Database - Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmaconnect
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.default_schema=public
spring.flyway.schemas=public
