spring.application.name=Pharmacy-Manager

# Database - Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmaconnect
spring.datasource.username=postgres
spring.datasource.password=10anidecasnicie
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always